In [1]:
import pandas as pd

In [9]:
dev_data = pd.read_csv("OpenForge_SOTAB_Benchmark/validation.csv")

In [11]:
dev_data["label_1_table_path"] = dev_data["label_1_table_path"].apply(lambda x: x.replace("/ssd/congtj/openforge/sotab_v2", "OpenForge_SOTAB_Benchmark"))
dev_data["label_2_table_path"] = dev_data["label_2_table_path"].apply(lambda x: x.replace("/ssd/congtj/openforge/sotab_v2", "OpenForge_SOTAB_Benchmark"))

In [12]:
dev_data

,label_1,label_2,label_1_processed,label_2_processed,label_1_table_path,label_2_table_path,label_1_col_idx,label_2_col_idx,name_qgram_similarity,name_jaccard_similarity,name_edit_distance,name_fasttext_similarity,name_word_count_ratio,name_char_count_ratio,value_jaccard_similarity,value_fasttext_similarity,original_relation_variable_name,relation_variable_label,relation_variable_name
0,CreativeWork/name,https://dbpedia.org/ontology/WrittenWork,creative work name,written work,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,0,1,0.133333,0.25,11,0.689210,1.5,1.500000,0.000000,0.723261,R_1-2,1,R_1-2
1,CreativeWork/name,Organization,creative work name,organization,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,0,5,0.052632,0.00,13,0.355463,3.0,1.500000,0.090909,0.405448,R_1-7,0,R_1-3
2,CreativeWork/name,https://dbpedia.org/ontology/dateTime,creative work name,date time,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,0,5,0.000000,0.00,12,0.374843,1.5,2.000000,0.090909,0.686472,R_1-10,0,R_1-4
3,CreativeWork/name,Boolean,creative work name,boolean,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,0,2,0.000000,0.00,16,0.133405,3.0,2.571429,0.000000,0.250213,R_1-11,0,R_1-5
4,CreativeWork/name,https://dbpedia.org/ontology/boolean,creative work name,boolean,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,0,5,0.000000,0.00,16,0.133405,3.0,2.571429,0.000000,0.250213,R_1-12,0,R_1-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,https://dbpedia.org/ontology/gender,weight,gender,weight,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,1,20,0.000000,0.00,5,0.226464,1.0,1.000000,0.000000,0.166145,R_86-89,0,R_43-45
1031,https://dbpedia.org/ontology/gender,Brand,gender,brand,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,1,4,0.000000,0.00,5,0.162878,1.0,1.200000,0.000000,0.260090,R_86-91,0,R_43-46
1032,https://dbpedia.org/ontology/distance,weight,distance,weight,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,21,22,0.000000,0.00,8,0.244275,1.0,1.333333,0.031250,0.935757,R_88-89,0,R_44-45
1033,https://dbpedia.org/ontology/distance,Brand,distance,brand,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,21,4,0.000000,0.00,6,0.070040,1.0,1.600000,0.000000,0.315216,R_88-91,0,R_44-46
1034,weight,Brand,weight,brand,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,5,6,0.000000,0.00,6,0.106290,1.0,1.200000,0.001742,0.359689,R_89-91,0,R_45-46

In [13]:
test_data = pd.read_csv("OpenForge_SOTAB_Benchmark/test.csv")
test_data["label_1_table_path"] = test_data["label_1_table_path"].apply(lambda x: x.replace("/ssd/congtj/openforge/sotab_v2", "OpenForge_SOTAB_Benchmark"))
test_data["label_2_table_path"] = test_data["label_2_table_path"].apply(lambda x: x.replace("/ssd/congtj/openforge/sotab_v2", "OpenForge_SOTAB_Benchmark"))

In [14]:
test_data

,label_1,label_2,label_1_processed,label_2_processed,label_1_table_path,label_2_table_path,label_1_col_idx,label_2_col_idx,name_qgram_similarity,name_jaccard_similarity,name_edit_distance,name_fasttext_similarity,name_word_count_ratio,name_char_count_ratio,value_jaccard_similarity,value_fasttext_similarity,original_relation_variable_name,relation_variable_label,relation_variable_name
0,Person/name,https://dbpedia.org/ontology/Person,person name,person,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,2,8,0.666667,0.5,5,0.665963,2.0,1.833333,0.000000,0.654410,R_3-4,1,R_1-2
1,Person/name,Language,person name,language,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,2,4,0.000000,0.0,8,0.287893,2.0,1.375000,0.250000,0.325645,R_3-5,0,R_1-3
2,Person/name,https://dbpedia.org/ontology/Language,person name,language,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,2,2,0.000000,0.0,8,0.287893,2.0,1.375000,0.000000,0.459259,R_3-6,0,R_1-4
3,Person/name,https://dbpedia.org/ontology/Organisation,person name,organisation,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,2,4,0.000000,0.0,10,0.283776,2.0,0.916667,0.000000,0.309142,R_3-8,0,R_1-5
4,Person/name,DateTime,person name,date time,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,2,2,0.000000,0.0,8,0.344967,1.0,1.222222,0.025000,0.347323,R_3-9,0,R_1-6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,https://dbpedia.org/ontology/rating,https://dbpedia.org/ontology/weight,rating,weight,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,3,16,0.000000,0.0,6,0.213561,1.0,1.000000,0.000000,0.507755,R_84-90,0,R_43-45
1031,https://dbpedia.org/ontology/rating,https://dbpedia.org/ontology/brand,rating,brand,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,3,2,0.000000,0.0,4,0.186224,1.0,1.200000,0.002358,0.530690,R_84-92,0,R_43-46
1032,Distance,https://dbpedia.org/ontology/weight,distance,weight,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,26,22,0.000000,0.0,8,0.244275,1.0,1.333333,0.054737,0.996111,R_87-90,0,R_44-45
1033,Distance,https://dbpedia.org/ontology/brand,distance,brand,OpenForge_SOTAB_Benchmark/cta_test_schemaorg/t...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,26,4,0.000000,0.0,6,0.070040,1.0,1.600000,0.000000,0.071676,R_87-92,0,R_44-46
1034,https://dbpedia.org/ontology/weight,https://dbpedia.org/ontology/brand,weight,brand,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,OpenForge_SOTAB_Benchmark/cta_test_dbpedia/tes...,3,5,0.000000,0.0,6,0.106290,1.0,1.200000,0.055556,0.416149,R_90-92,0,R_45-46

In [15]:
def few_shots(n=10, balanced=True):
    if not balanced:
        return dev_data.sample(n)
    rst = pd.concat([dev_data[dev_data['relation_variable_label'] == 1].sample(n//2), dev_data[dev_data['relation_variable_label'] == 0].sample(n - n//2)])
    rst = rst.sample(frac=1)
    return rst[['label_1_processed', 'label_2_processed', 'relation_variable_label', 'label_1_table_path', 'label_2_table_path', 'label_1_col_idx', 'label_2_col_idx']]

In [31]:
def sample_column_value(table_path, col_id, n=5):
    table = pd.read_json(table_path, compression="gzip", lines=True)
    table = table.astype(str)
    k = n
    rst = table[col_id].unique().tolist()[:k]
    while len("".join(rst)) > 300:
        k -= 1
        rst = table[col_id].unique().tolist()[:k]
    if k:
        return table[col_id].unique().tolist()[:k]
    else:
        return table[col_id].unique().tolist()[:1]

In [32]:
sample_column_value("OpenForge_SOTAB_Benchmark/cta_test_schemaorg/test/CreativeWork_milesnsmilesholidays.com_September2020_CTA.json.gz", 0)

["['Do I need to get any specific vaccinations before visting Australia?', 'What tips are recommended for the guests?', 'What things are prohibited to bring in Australia?', 'What languages are spoken in Australia?', 'What is the weather & climate like in Australia genrally?', 'What is the best time to travel?']"]

In [33]:
fewshots_prompt = "\n\n".join(["Input:\nLabel 1: {}\nSample Column Value for Label 1:\n{}\n\nLabel 2: {}\nSample Column Value for Label 2:\n{}\n\nOutput:\n{}".format(row[0], sample_column_value(row[3], row[5]), row[1], sample_column_value(row[4], row[6]), '{"answer": "yes"}' if row[2] else '{"answer": "no"}') for row in few_shots().values.tolist()])

In [48]:
prompts = []
labels = []

for _, row in test_data.iterrows():
    prompt = """Column semantic types are used to describe the semantic type of a table column. Different systems use sementic type labels from different ontologies, your task is to determine whether two sementic types are equivelant. For each input label, you will also be provided with sample column values from columns labeled with the input label. Return your final result in the following JSON format : {"answer": <yes or no>}.

For example:

"""
    fewshots_prompt = "\n\n".join(["Input:\nLabel 1: {}\nSample Column Value for Label 1:\n{}\n\nLabel 2: {}\nSample Column Value for Label 2:\n{}\n\nOutput:\n{}".format(row[0], sample_column_value(row[3], row[5]), row[1], sample_column_value(row[4], row[6]), '{"answer": "yes"}' if row[2] else '{"answer": "no"}') for row in few_shots().values.tolist()])
    prompt += fewshots_prompt
    prompt += """

Now, for the following label pairs, please determine if they are equivelant. Return your final result in the following JSON format : {{"answer": <yes or no>}}.

Input:
Label 1: {}
Sample Column Value for Label 1:
{}

Label 2: {}
Sample Column Value for Label 2:
{}

Output:
    """.format(row['label_1_processed'], sample_column_value(row['label_1_table_path'], row['label_1_col_idx']), row['label_2_processed'], sample_column_value(row['label_2_table_path'], row['label_2_col_idx']))
    prompts.append(prompt)
    labels.append(row['relation_variable_label'])

In [49]:
print(prompts[0])

Column semantic types are used to describe the semantic type of a table column. Different systems use sementic type labels from different ontologies, your task is to determine whether two sementic types are equivelant. For each input label, you will also be provided with sample column values from columns labeled with the input label. Return your final result in the following JSON format : {"answer": <yes or no>}.


For the following label pairs, please determine if they are equivelant. Return your final result in the following JSON format : {"answer": <yes or no>}.

Input:
Label 1: person name
Sample Column Value for Label 1:
['None', 'Swati Dave', 'ayushi saini']

Label 2: person
Sample Column Value for Label 2:
['Carole Stivers', 'Akwaeke Emezi', 'Raven Leilani', 'Megan Goldin', 'Tamsyn Muir']

Output:

In [50]:
labels[0]

1

In [51]:
df = pd.DataFrame({"prompt": prompts, "label": labels})

In [52]:
df.head()

                                              prompt  label
0  Column semantic types are used to describe the...      1
1  Column semantic types are used to describe the...      0
2  Column semantic types are used to describe the...      0
3  Column semantic types are used to describe the...      0
4  Column semantic types are used to describe the...      0

In [44]:
df.shape

(1035, 2)

In [53]:
df.to_json("sotab_test_w_sample_value_0shots.jsonl", orient="records", lines=True)

In [56]:
prompts = []
labels = []

for _, row in test_data.iterrows():
    prompt = """Column semantic types are used to describe the semantic type of a table column. Different systems use sementic type labels from different ontologies, your task is to determine whether two sementic types are equivelant. Return your final result in the following JSON format : {"answer": <yes or no>}.

For example:

"""
    fewshots_prompt = "\n\n".join(["Input:\nLabel 1: {}\nLabel 2: {}\nOutput:\n{}".format(row[0], row[1], '{"answer": "yes"}' if row[2] else '{"answer": "no"}') for row in few_shots().values.tolist()])
    prompt += fewshots_prompt
    prompt += """

Now, for the following label pairs, please determine if they are equivelant. Return your final result in the following JSON format : {{"answer": <yes or no>}}.

Input:
Label 1: {}
Label 2: {}

Output:
    """.format(row['label_1_processed'], row['label_2_processed'])
    prompts.append(prompt)
    labels.append(row['relation_variable_label'])

df = pd.DataFrame({"prompt": prompts, "label": labels})
df.to_json("sotab_test_10shots.jsonl", orient="records", lines=True)

## Evaluate

In [85]:
from sklearn.metrics import f1_score, accuracy_score, recall_score
import re
def evaluate(file):
    df = pd.read_json(file, lines=True)
    y_pred, y_true = [], []
    for _, row in df.iterrows():
        label = row['label']
        res = row['response']
        pattern = r'{[^}]*}'
        matches = re.findall(pattern, res)
        res = json.loads(matches[0].strip())
        y_true.append(label)
        pred = 1 if res['answer'] == "yes" else 0
        y_pred.append(pred)
    f1 = f1_score(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)
    rc = recall_score(y_true, y_pred)
    print("f1: {:.5f}\nacc: {:.5f}\nrecall: {:.5f}".format(f1, acc, rc))

In [76]:
evaluate("sotab_test_w_sample_value_0shots.jsonl.gpt-3.5-turbo-1106.result.jsonl")

f1: 0.61538
acc: 0.99034
recall: 0.61538

In [77]:
evaluate("sotab_test_w_sample_value_10shots.jsonl.gpt-3.5-turbo-1106.result.jsonl")

f1: 0.47059
acc: 0.99118
recall: 0.30769

In [87]:
evaluate("sotab_test_10shots.jsonl.gpt-3.5-turbo-1106.result.jsonl")

f1: 0.72727
acc: 0.99130
recall: 0.92308

In [86]:
evaluate("sotab_test_w_sample_value_0shots.jsonl.gpt-4.result.jsonl")

f1: 0.75000
acc: 0.99226
recall: 0.92308

In [88]:
evaluate("sotab_test_w_sample_value_10shots.jsonl.gpt-4.result.jsonl")

f1: 0.75000
acc: 0.99227
recall: 0.92308

In [89]:
evaluate("sotab_test_10shots.jsonl.gpt-4.result.jsonl")

f1: 0.55000
acc: 0.98261
recall: 0.84615

## Evaluate GPT4

In [52]:
gpt_4 = pd.read_json("./sotab_test.jsonl.gpt-4.result.jsonl", lines=True)

In [53]:
gpt_4

,prompt,label,response
0,Column semantic types are used to describe the...,1,"{""answer"": ""no""}"
1,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
2,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
3,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
4,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
...,...,...,...
1028,Column semantic types are used to describe the...,1,"{""answer"": ""no""}"
1029,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
1030,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
1031,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"
1032,Column semantic types are used to describe the...,0,"{""answer"": ""no""}"

In [55]:
import json
y_pred, y_true = [], []
for _, row in gpt_4.iterrows():
    label = row['label']
    try:
        res = json.loads(row['response'])
    except:
        continue
    y_true.append(label)
    y_pred.append(1 if res['answer'] == "yes" else 0)

In [56]:
f1_score(y_true, y_pred)

0.4

In [57]:
accuracy_score(y_true, y_pred)

0.970873786407767

In [58]:
recall_score(y_true, y_pred)

0.7692307692307693